# Generated by Django 3.1 on 2020-08-30 09:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fancypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fancypage',
            name='body',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('sub_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('link_1', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(required=False))], required=True)), ('link_2', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(required=False))], required=True))]))]),
        ),
    ]
