# Generated by Django 3.1 on 2020-08-30 11:10

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fancypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fancypage',
            name='body',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('sub_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(validators=(home.models.title_field_validator,))), ('content', wagtail.core.blocks.RichTextBlock(features=['ol', 'bold'])), ('link_1', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(required=False))])), ('link_2', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(required=False))]))])), ('image_gallery', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))], max_num=16))]),
        ),
    ]
